version: "3.9"


services:

    ####################################################################################################
    # Back-end
    ####################################################################################################
    eBack:
      image: eBack
      build: ./eBack
      working_dir: /var/www/
      volumes:
        - ./eBack:/var/www/
        - ./eBack/public/:/var/www/html/
      ports:
        - 8200:80
      depends_on:
        - eBb
    ####################################################################################################
    # Front-end
    ####################################################################################################
    eFront:
      image: node:latest
      working_dir: /app
      command: "npm run start"
      volumes:
        - ./eFront:/app
      ports:
        - 3000:3000
      depends_on:
        - eBack

    ####################################################################################################
    # DATABASE (PostgreSQL)
    ####################################################################################################
    eBb:
        image: postgres:latest
        environment:
          POSTGRES_PASSWORD: mm1dari13
          POSTGRES_USER: etovar
          POSTGRES_DB: edashboard-db
        volumes:
          - ./sql/setup.sql:/docker-entrypoint-initdb.d/init.sql
        ports:
          - "5432:5432"
    ####################################################################################################
    # DATABASE (UI)
    ####################################################################################################     

    adminer:
      image: adminer
      restart: always
      ports:
        - 8080:8080